### PR TITLE
Fix csv unicode

### LINKED ISSUE #1: CSV import fails on unicode characters

### PR DESCRIPTION
**Pull request by rkkautsar**
tested in local, fixes #1

### CODE REVIEW

**Comment by rkkautsar** [comment]
using default docker-compose.yml generates MySQL error:
```
InternalError: (pymysql.err.InternalError) (1267, u"Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='") [SQL: u'SELECT teams.id AS teams_id, teams.name AS teams_name, teams.email AS teams_email, teams.password AS teams_password, teams.website AS teams_website, teams.affiliation AS teams_affiliation, teams.country AS teams_country, teams.bracket AS teams_bracket, teams.banned AS teams_banned, teams.verified AS teams_verified, teams.`admin` AS teams_admin, teams.joined AS teams_joined, name \nFROM teams \nWHERE teams.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {u'name_1': u"(\u0e07'\u0300-'\u0301)\u0e07", u'param_1': 1}]
```

**Comment by rkkautsar** [comment]
Can conirm this is caused by default encoding of MySQL is not UTF-8, solved by [specifying mysql cnf](https://stackoverflow.com/a/3513812)

**Comment by farisv** [comment]
Seems like, this issue can be fixed by changing `name = team[0]` to `name = team[0].decode('utf-8')`. So, we don't need to add dependency to additional library (`unicodecsv`).

Can you please try my suggestion and confirm that can fix unicode issue for your case?

**Comment by rkkautsar** [comment]
Confirmed, will revise the PR soon

**Comment by farisv** [comment]
Oops, I just see your message. I already push my commits for ` decode('utf-8')` trick.

**Comment by rkkautsar** [comment]
Yup, that's ok, thanks for the plugin

**Pull request closed without merging**
